version: "3"
services:
  db:
    container_name: htmx-test-db
    image: mysql:8.0
    volumes:
      - db-store:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: hogehoge
      MYSQL_DATABASE: db_dev
      MYSQL_USER: admin
      MYSQL_PASSWORD: hogehoge
      TZ: "Asia/Tokyo"
    command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci
    healthcheck:
      test: mysqladmin ping
      interval: 15s
      retries: 5

  web:
    container_name: htmx-test
    build: .
    volumes:
      - ./htmx_test:/app
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
    tty: true
    stdin_open: true

volumes:
  db-store:
